### ISSUE TITLE
Wheel and auditwheel from conda-forge appear to be incompatible

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/auditwheel-feedstock#29]
It seems that the latest versions of wheel and auditwheel from conda-forge are not compatible with each other.

``` 
> audit wheel show foobar.whl
Traceback (most recent call last):
  File "/home/sylvain/miniconda3/bin/auditwheel", line 10, in <module>
    sys.exit(main())
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/auditwheel/main.py", line 50, in main
    rval = args.func(args, p)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/auditwheel/main_show.py", line 26, in execute
    from .wheel_abi import analyze_wheel_abi
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/auditwheel/wheel_abi.py", line 12, in <module>
    from .genericpkgctx import InGenericPkgCtx
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/auditwheel/genericpkgctx.py", line 1, in <module>
    from .wheeltools import InWheelCtx
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/auditwheel/wheeltools.py", line 15, in <module>
    from wheel.util import urlsafe_b64encode, open_for_csv, native  # type: ignore
ImportError: cannot import name 'open_for_csv' from 'wheel.util' (/home/sylvain/miniconda3/lib/python3.7/site-packages/wheel/util.py)
```

```
> conda list | grep wheel
auditwheel                2.1.0            py37hc8dfbb8_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
```

**Comment by jakirkham** [comment]
Are you still seeing this Sylvain?

**Comment by jakirkham** [comment]
Going to close this out, but please feel free to reopen if this is still an issue
