### ISSUE TITLE
Import error without `setuptools`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/auditwheel-feedstock#5]
~~Looks like this needs to be updated to have proper entrypoints.~~ Appears this requires `setuptools` and `pip` at run-time. See the snippet below taken from this [log]( https://circleci.com/gh/conda-forge/auditwheel-feedstock/7 ).

```
Traceback (most recent call last):
  File "/opt/conda/envs/_test/bin/auditwheel", line 6, in <module>
    from auditwheel.main import main
  File "/opt/conda/envs/_test/lib/python3.4/site-packages/auditwheel/main.py", line 5, in <module>
    import pkg_resources
ImportError: No module named 'pkg_resources'
TESTS FAILED: auditwheel-1.1.0-py34_0
```

**Comment by jakirkham** [comment]
Looks like `pkg_resources` is being [imported]( https://github.com/pypa/auditwheel/blob/1.1/auditwheel/main.py#L5 ). So, we just require `setuptools` at run-time.

**Comment by jakirkham** [comment]
Apparently also [imports]( https://github.com/pypa/auditwheel/blob/1.1/auditwheel/policy/versioned_symbols.py#L3 ) `pip`. This looks kind of ugly as it is importing a `_` prefixed module.
